server:
  port: 7001

eureka:
  instance:
    hostname: localhost   #eureka服务端的实例名称
#    hostname: eureka7001.com
  client:
    # 不向服务端注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址，查询和注册服务都需要用到
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://eureka7002.com:7002/eureka/
  #关闭保护机制，默认为true，和心跳间隔
  #关闭后：THE SELF PRESERVATION MODE IS TURNED OFF. THIS MAY NOT PROTECT INSTANCE EXPIRY IN CASE OF NETWORK/OTHER PROBLEMS.
  server:
    enable-self-preservation: true
#    eviction-interval-timer-in-ms: 20000