server:
  port: 3344

spring:
  application:
    name: cloud-config-centere
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fy-66/springcloud-config.git
          #搜索目录
          search-paths:
            - springcloud-config
      label: main   #读取分支
#eureka
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka

#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
