server:
  port: 3344

spring:
  application:
    name: cloud-config-centere
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fy-66/springcloud-config.git
          #搜索目录
          search-paths:
            - springcloud-config
      label: main   #读取分支
  rabbitmq:
    host: 192.168.33.33
    port: 5672
    username: root
    password: 123456

#eureka
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka


#rabbitmq相关配置，暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
