server:
  port: 8008

spring:
  application:
    name: consul-provider-hystrix-payment

eureka:
  client:
    #表示将自己注册进eureka server，默认为true
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须为true，才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
            defaultZone: http://eureka7001.com:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    #在eureka中显示 项目名 和 ip
    instance-id: payment8008
    prefer-ip-address: true