server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
      host: 192.168.33.33
      port: 8500

