server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
#          uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #从服务中心匹配后，提供服务路由地址
          predicates:
            - Path=/payment/get/**          #断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_routh   #路由的ID，没有固定规则但要求唯一，简易配合服务名
#          uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #从服务中心匹配后，提供服务路由地址
          filters:
#            - AddRequestParameter=uname,\d+
          predicates:
            - Path=/payment/lb/**             #断言，路径相匹配的进行路由
            #- After=2021-05-13T10:23:04.250+08:00[Asia/Shanghai]  #时间之后才能匹配
            #- Cookie=username,zzyy
            #- Query=username,\d+
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    #表示将自己注册进eureka server，默认为true
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须为true，才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
