server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.33.33:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"